//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace PCPPartsExpress {
    
    
    public partial class Account {
        
        /// <summary>
        /// lblAccName control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Label lblAccfName;
        protected global::System.Web.UI.WebControls.Label lblAcclName;

        /// <summary>
        /// lblAccAddress control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Label lblAccAddress;
        
        /// <summary>
        /// lblAccSSP control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Label lblAccSSP;
        
        /// <summary>
        /// lblAccPhoneNumber control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Label lblAccPhoneNumber;
        
        /// <summary>
        /// lblAccEmail control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Label lblAccEmail;
        
        /// <summary>
        /// lblAccName2 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Label lblAccName2;
        protected global::System.Web.UI.WebControls.TextBox txtAccfName;
        protected global::System.Web.UI.WebControls.TextBox txtAcclName;
        protected global::System.Web.UI.WebControls.TextBox txtAccAddress;
        protected global::System.Web.UI.WebControls.TextBox txtAccPhoneNumber;
        protected global::System.Web.UI.WebControls.Button EditDetailsbtn;
        protected global::System.Web.UI.WebControls.Button EditConfirmbtn;
    }
}
