//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PCPPartsExpress.User_Layer
{


    public partial class AddItem
    {
        //globals to add controls to add item page

        protected global::System.Web.UI.WebControls.Panel AddItemPanel;

        protected global::System.Web.UI.WebControls.Label lblproductname;
        protected global::System.Web.UI.WebControls.TextBox txtbxproductname;
        protected global::System.Web.UI.WebControls.RequiredFieldValidator rfvproductname;

        protected global::System.Web.UI.WebControls.Label lblcategory;
        protected global::System.Web.UI.WebControls.DropDownList ddlcategory;
        protected global::System.Web.UI.WebControls.RequiredFieldValidator rfvcategory;

        protected global::System.Web.UI.WebControls.Label lblmodel;
        protected global::System.Web.UI.WebControls.TextBox txtbxmodel;
        protected global::System.Web.UI.WebControls.RequiredFieldValidator rfvmodel;

        protected global::System.Web.UI.WebControls.Label lblmanufacturer;
        protected global::System.Web.UI.WebControls.TextBox txtbxmanufacturer;
        protected global::System.Web.UI.WebControls.RequiredFieldValidator rfvmanufacturer;

        protected global::System.Web.UI.WebControls.Label lblprice;
        protected global::System.Web.UI.WebControls.TextBox txtbxprice;
        protected global::System.Web.UI.WebControls.RequiredFieldValidator rfvprice;
        protected global::System.Web.UI.WebControls.RegularExpressionValidator regexprice;

        protected global::System.Web.UI.WebControls.Label lblstock;
        protected global::System.Web.UI.WebControls.TextBox txtbxstock;
        protected global::System.Web.UI.WebControls.RequiredFieldValidator rfvstock;
        protected global::System.Web.UI.WebControls.RegularExpressionValidator regexstock;

        protected global::System.Web.UI.WebControls.Label lbldescription;
        protected global::System.Web.UI.WebControls.TextBox txtbxdescription;
        protected global::System.Web.UI.WebControls.RequiredFieldValidator rfvdescription;

        protected global::System.Web.UI.WebControls.Label lblreleasedate;
        protected global::System.Web.UI.WebControls.TextBox txtbxreleasedate;
        protected global::System.Web.UI.WebControls.RequiredFieldValidator rfvreleasedate;

        protected global::System.Web.UI.WebControls.Label lblconfirmation;

        protected global::System.Web.UI.WebControls.Button SubmitButton;

    }
}
