//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace PCPPartsExpress {
    
    
    public partial class Payment {
        
        /// <summary>
        /// Confirmation control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Button Confirmation;

        protected global::System.Web.UI.WebControls.Label lblCardName;
        protected global::System.Web.UI.WebControls.Label lblCardNumber;
        protected global::System.Web.UI.WebControls.Label lblCVC;
        protected global::System.Web.UI.WebControls.Label lblExpiry;
        protected global::System.Web.UI.WebControls.Label lblPrice;
        protected global::System.Web.UI.WebControls.Label lblPriceTotal;
        protected global::System.Web.UI.WebControls.Label lblDescription;
        protected global::System.Web.UI.WebControls.Label lblOrderDescription;

        protected global::System.Web.UI.WebControls.TextBox txtbxCardName;
        protected global::System.Web.UI.WebControls.TextBox txtbxCardNumber;
        protected global::System.Web.UI.WebControls.TextBox txtbxCVC;
        protected global::System.Web.UI.WebControls.TextBox txtbxYear;
        protected global::System.Web.UI.WebControls.TextBox txtbxMonth;
        protected global::System.Web.UI.WebControls.TextBox txtbxDay;


        protected global::System.Web.UI.WebControls.Label lblPaymentStatus;
        protected global::System.Web.UI.WebControls.Label lblPayment;
    }
}
