//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PCPPartsExpress.User_Layer
{


    public partial class ProductDetail
    {
        protected global::System.Web.UI.WebControls.Label lblProductName;
        protected global::System.Web.UI.WebControls.Label lblPrice;
        protected global::System.Web.UI.WebControls.Label lblStock;
        protected global::System.Web.UI.WebControls.Label lblStock2;
        protected global::System.Web.UI.WebControls.Button AddToCartBtn;
        protected global::System.Web.UI.WebControls.Label lblDescription;
        protected global::System.Web.UI.WebControls.Label lblManufacturer;
        protected global::System.Web.UI.WebControls.Label lblModel;
        protected global::System.Web.UI.WebControls.Label lblReleaseDate;
        protected global::System.Web.UI.WebControls.Label breadcrumref;
        protected global::System.Web.UI.WebControls.Label catref;

        protected global::System.Web.UI.WebControls.TextBox txtbxProductName;
        protected global::System.Web.UI.WebControls.TextBox txtbxPrice;
        protected global::System.Web.UI.WebControls.TextBox txtbxStock;
        protected global::System.Web.UI.WebControls.TextBox txtbxDescription;
        protected global::System.Web.UI.WebControls.TextBox txtbxManufacturer;
        protected global::System.Web.UI.WebControls.TextBox txtbxModel;
        protected global::System.Web.UI.WebControls.TextBox txtbxReleaseDate;
        protected global::System.Web.UI.WebControls.Button btnSave;
        protected global::System.Web.UI.WebControls.Button btnEditPage;
    
    }
}
